-- MATH-ROOM SUPABASE SETUP SCRIPT
-- Copy and paste this into your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. PROFILES TABLE (Extends Auth.Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL UNIQUE,
    teacher_email TEXT NOT NULL,
    teacher_name TEXT NOT NULL,
    topic TEXT DEFAULT '',
    difficulty TEXT DEFAULT 'Medium',
    max_students INTEGER DEFAULT 30,
    total_students INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'ended')),
    started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    duration_minutes INTEGER DEFAULT 0
);

-- 3. STUDENT NOTES TABLE
CREATE TABLE IF NOT EXISTS public.student_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_email TEXT NOT NULL,
    student_display_name TEXT NOT NULL,
    room_code TEXT NOT NULL,
    title TEXT DEFAULT 'Catatan Tanpa Judul',
    canvas_data JSONB NOT NULL,
    thumbnail TEXT, -- Base64 thumbnail string
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. PROBLEM TABLES
CREATE TABLE IF NOT EXISTS public.problem_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic TEXT NOT NULL,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('Easy', 'Medium', 'Hard', 'Expert')),
    problem_type TEXT DEFAULT 'template',
    template_function TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.session_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE,
    room_code TEXT NOT NULL,
    problem_number INTEGER NOT NULL,
    topic TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(room_code, problem_number)
);

CREATE TABLE IF NOT EXISTS public.student_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT REFERENCES public.session_problems(id) ON DELETE CASCADE,
    student_email TEXT NOT NULL,
    student_name TEXT NOT NULL,
    selected_answer TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    answered_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    scratch_canvas_data JSONB,
    time_spent_seconds INTEGER DEFAULT 0,
    UNIQUE(problem_id, student_email)
);

-- 5. ENABLE REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE student_notes;

-- 6. SET UP ROW LEVEL SECURITY (RLS)
-- Note: Applying basic "public access" for now. In production, you should refine these policies.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.problem_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_answers ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read/write (Simplified for training app)
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow public read access to sessions" ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert to sessions" ON public.sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to sessions" ON public.sessions FOR UPDATE USING (true);

CREATE POLICY "Allow public read access to student_notes" ON public.student_notes FOR SELECT USING (true);
CREATE POLICY "Allow public insert to student_notes" ON public.student_notes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete to student_notes" ON public.student_notes FOR DELETE USING (true);

CREATE POLICY "Allow public access to problem tables" ON public.problem_templates FOR ALL USING (true);
CREATE POLICY "Allow public access to session_problems" ON public.session_problems FOR ALL USING (true);
CREATE POLICY "Allow public access to student_answers" ON public.student_answers FOR ALL USING (true);
