useCaseDiagram
    actor Teacher as 👨‍🏫 GURU
    
    package Math-Room-System {
        usecase UC1 as "🔑 Login Akun"
        usecase UC2 as "📝 Buat & Atur Ruangan"
        usecase UC3 as "📡 Monitor Dashboard Real-time"
        usecase UC4 as "📹 Pantau Video/Audio Siswa"
        usecase UC5 as "🛑 Akhiri Sesi Belajar"
    }

    Teacher --> UC1
    Teacher --> UC2
    Teacher --> UC3
    Teacher --> UC4
    Teacher --> UC5
