useCaseDiagram
    actor Student as 🎓 SISWA
    
    package Math-Room-System {
        usecase US1 as "🔑 Login Akun"
        usecase US2 as "🔢 Join Ruangan via Kode"
        usecase US3 as "✏️ Menggambar & Belajar"
        usecase US4 as "📐 Gunat Alat Matematika"
        usecase US5 as "💾 Simpan & Lihat Catatan"
    }

    Student --> US1
    Student --> US2
    Student --> US3
    Student --> US4
    Student --> US5
